spring:
  application:
    name: EAccount
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3307/dataagg?useUnicode = true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull"
    username: dataagg
    password: EdIyNje2GsRyzPDXQfp1

server:
  context-path: /EAccount
  port: 6000

logging:
  level:
    root: WARN

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://service-center:8761/eureka/

security:
  oauth2:
    resource:
      EUser-info-uri: http://security:5000/security/users/current
    client:
      clientId: EAccount
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://security:5000/security/oauth/token
      grant-type: client_credentials
      scope: server

