spring:
  application:
    name: api-gateway
server:
  port: 80
logging:
  level:
    root: WARN
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-center:8761/eureka/
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    security:
      path: /security/**
      serviceId: security
    account:
      path: /account/**
      serviceId: account
