spring:
  application:
    name: apigateway

server:
  port: 4000

logging:
  level:
    root: WARN

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://service-center:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://security:5000/uaa/users/current

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    security:
        path: /uaa/**
        url: http://security:5000
        stripPrefix: false
        sensitiveHeaders:

    payment:
        path: /payment/**
        serviceId: http://payment:6000
        stripPrefix: false
        sensitiveHeaders:
