spring:
  application:
    name: service-center
server:
  port: 8761

logging:
  level:
    root: WARN

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

security:
  oauth2:
    resource:
      user-info-uri: http://security:5000/uaa/users/current