spring:
  application:
    name: service-center
server:
  context-path: /service-center
  port: 8761
logging:
  level:
    root: WARN
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
