spring:
  application:
    name: security
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dataagg?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: dataagg
    password: EdIyNje2GsRyzPDXQfp1
server:
  context-path: /security
  port: 5000
logging:
  level:
    root: info
    com.dataagg: debug
    org.springframework.boot.context.embedded: INFO
