security:
  oauth2:
    client:
      clientId: account
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://security:5000/security/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/dataagg?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull"
    username: dataagg
    password: EdIyNje2GsRyzPDXQfp1

server:
  context-path: /account
  port: 6000
