logging:
  level:
    root: WARN
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://service-center:8761/eureka/

security:
  oauth2:
    resource:
      EUser-info-uri: http://security:5000/security/users/current

spring:
  rabbitmq:
    host: rabbitmq
